// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLAjlaFwLpB8nR-0WNWUCxZwbwmy96nk',
    appId: '1:968629153457:web:5ef0898e2e2e438df6fc90',
    messagingSenderId: '968629153457',
    projectId: 'gico-services',
    authDomain: 'gico-services.firebaseapp.com',
    databaseURL: 'https://gico-services-default-rtdb.firebaseio.com',
    storageBucket: 'gico-services.appspot.com',
    measurementId: 'G-KLK1E6FVBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyLepC1i-3KAqRSFg01QOMpzmCzj2boc',
    appId: '1:968629153457:android:988495420ad63508f6fc90',
    messagingSenderId: '968629153457',
    projectId: 'gico-services',
    databaseURL: 'https://gico-services-default-rtdb.firebaseio.com',
    storageBucket: 'gico-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3Ob5sh98M3Elqi9_WDfKpeYfEY8MBwI',
    appId: '1:968629153457:ios:900f8bfab1416e7bf6fc90',
    messagingSenderId: '968629153457',
    projectId: 'gico-services',
    databaseURL: 'https://gico-services-default-rtdb.firebaseio.com',
    storageBucket: 'gico-services.appspot.com',
    iosClientId: '968629153457-8av59ic047sshvl32tv94mrftrtt0o06.apps.googleusercontent.com',
    iosBundleId: 'com.gico.service',
  );
}
